---
# tasks file for jenkins_install
#- hosts: all
#  become: true
#  tasks: 
   - name: java_installation
     command: "sudo yum install java"
   - name: jenkins_download 
     command: "sudo wget -O /etc/yum.repos.d/jenkins.repo http://pkg.jenkins-ci.org/redhat/jenkins.repo"
   - name: jenkins_key_download
     command: "sudo rpm --import http://pkg.jenkins-ci.org/redhat/jenkins-ci.org.key"
   - name: jenkins_install
     command: "sudo yum install -y jenkins"
   - name: jenkins_start
     command: "sudo service jenkins start"
    
